import Link from 'next/link';
import { ArrowDownRight, ArrowUpRight, Sparkles } from 'lucide-react';
import AboutOrbit from '../../components/AboutOrbit';
import BrandMark from '../../components/BrandMark';

export default function SobrePage() { return <main className="inner-page">
  <nav className="inner-nav"><Link className="brand" href="/"><BrandMark className="brand-mark-text"/><span>SALUTAR<span className="dot">.</span></span></Link><div className="nav-links"><Link href="/">Início</Link><Link href="/sobre">Sobre nós</Link><Link href="/contato">Contato</Link></div><Link className="nav-cta" href="https://wa.me/553192288682?text=Olá%20Salutar%2C%20quero%20iniciar%20um%20projeto." target="_blank">Vamos conversar <ArrowUpRight size={16}/></Link></nav>
  <section className="inner-hero about-page-hero"><div><p className="eyebrow"><Sparkles size={14}/> Nossa história</p><h1>Ideias que<br/><em>ganham vida.</em></h1><p className="inner-lead">A Salutar é feita por amigos que transformam inquietação, marketing e tecnologia em novas possibilidades para marcas.</p></div><div className="about-page-orbit"><AboutOrbit/></div></section>
  <section className="story-section"><p className="eyebrow dark"><span>01</span> De onde viemos</p><div className="story-grid"><h2>Amigos, ambição<br/>e vontade de<br/><em>fazer diferente.</em></h2><div><p>A Salutar nasceu da conversa entre um grupo de amigos ambiciosos, apaixonados por marketing, tecnologia e pela possibilidade de criar algo que realmente mudasse o jogo.</p><p>Começamos com uma pergunta simples: e se a internet pudesse ser mais humana, mais criativa e mais útil para quem está construindo um negócio? Desde então, transformamos estratégia, design e código em caminhos para marcas encontrarem seu espaço.</p><p>Acreditamos que não basta acompanhar a evolução da internet. É preciso participar dela, criando experiências que conectam, geram movimento e deixam uma marca positiva no mundo.</p></div></div></section>
  <section className="belief-section"><p className="eyebrow"><span>02</span> O que nos move</p><h2>Estratégia com<br/><em>energia humana.</em></h2><Link className="big-link" href="/contato">Começar uma conversa <span><ArrowDownRight/></span></Link></section>
 </main>; }
