'use client';

import dynamic from 'next/dynamic';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, BarChart3, Camera, Clapperboard, Globe2, Instagram, Menu, MousePointer2, Search, Send, Sparkles, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import BrandMark from './BrandMark';
const OrbitScene = dynamic(() => import('./OrbitScene'), { ssr: false });
const services = [
  ['01','Tráfego Pago','Campanhas de anúncios estratégicas que atraem clientes certos e aceleram resultados.',MousePointer2,'orange'],
  ['02','SEO','Seu site no topo do Google. Mais visibilidade, mais tráfego, mais vendas — de forma orgânica e duradoura.',Search,'aqua'],
  ['03','Social Media','Presença profissional e ativa nas redes sociais, com design, vídeo e estratégia trabalhando juntos pela sua marca.',Instagram,'electric'],
  ['04','Criação de Sites','Sites que transmitem credibilidade e facilitam o primeiro contato com seu cliente.',Globe2,'lilac'],
  ['05','Vídeo e Edição','Conteúdo audiovisual de qualidade que capta atenção e fortalece sua marca em qualquer formato.',Clapperboard,'gold'],
  ['06','Fotografia','Imagens profissionais que valorizam sua marca e seus produtos.',Camera,'aqua'],
  ['07','Consultoria','Um olhar externo e especializado que identifica gargalos e aponta o caminho para sua operação crescer.',BarChart3,'orange'],
] as const;
const serviceDetails: Record<string, string> = {
 'Tráfego Pago': 'Planejamos, criamos e otimizamos campanhas para colocar sua marca na frente das pessoas certas, no momento certo.',
 SEO: 'Estruturamos conteúdo, palavras-chave e experiência técnica para seu site conquistar relevância e crescer de forma sustentável.',
 'Social Media': 'Cuidamos do calendário, identidade visual, produção e interação para transformar seus canais em pontos de contato vivos.',
 'Criação de Sites': 'Desenhamos páginas rápidas, responsivas e estratégicas, feitas para apresentar seu negócio e facilitar conversas.',
 'Vídeo e Edição': 'Da ideia ao corte final, criamos vídeos que traduzem sua mensagem e funcionam em anúncios, reels e campanhas.',
 Fotografia: 'Produzimos imagens com direção e tratamento profissional para mostrar o valor da sua marca em cada detalhe.',
 Consultoria: 'Analisamos sua operação de fora para dentro, encontramos oportunidades e organizamos próximos passos mais claros.',
};
export default function AgencySite() {
 const [menu,setMenu]=useState(false); const [activeService,setActiveService]=useState<string | null>(null); const ticker=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(ticker.current) gsap.to(ticker.current,{xPercent:-50,duration:18,repeat:-1,ease:'none'});const c=document.querySelector<HTMLAnchorElement>('.nav-cta');if(c)c.href='https://wa.me/553192288682?text=Ol%C3%A1%20Salutar%2C%20quero%20iniciar%20um%20projeto.';document.querySelectorAll<HTMLAnchorElement>('a[href="#sobre"]').forEach(a=>a.href='/sobre');document.querySelectorAll<HTMLAnchorElement>('a[href="#contato"]').forEach(a=>a.href='/contato');const cards=Array.from(document.querySelectorAll<HTMLElement>('.service-card'));const toggle=(event:Event)=>{const card=event.currentTarget as HTMLElement;cards.forEach(item=>{if(item!==card)item.classList.remove('is-open');});card.classList.toggle('is-open');};cards.forEach(card=>card.addEventListener('click',toggle));return()=>cards.forEach(card=>card.removeEventListener('click',toggle));},[]);
 useEffect(()=>{const details=['Estratégia, segmentação e otimização contínua para transformar investimento em mídia em oportunidades reais. Criamos campanhas, testes e criativos que atraem o público certo e aceleram o crescimento da sua marca.','Conteúdo, técnica e autoridade para seu site ser encontrado por quem já procura o que você oferece. Trabalhamos estrutura, palavras-chave e experiência para construir visibilidade orgânica consistente.','Planejamento editorial, direção criativa, design e edição para transformar suas redes em uma presença ativa, reconhecível e próxima. Cada publicação nasce com intenção e conversa com a sua estratégia.','Uma experiência digital bonita, rápida e clara, pensada para transmitir confiança e conduzir o visitante até o próximo passo. Do conceito ao lançamento, o site trabalha a favor do seu negócio.','Roteiros, captação, montagem e finalização para criar vídeos que param o scroll e fazem sua mensagem permanecer. Produzimos peças para campanhas, redes sociais e comunicação institucional.','Direção, luz e tratamento para revelar o melhor da sua marca, dos seus produtos e das pessoas por trás deles. Fotos profissionais aumentam percepção de valor e dão consistência à comunicação.','Um olhar experiente para encontrar gargalos, organizar prioridades e transformar dúvidas em decisões. A consultoria entrega clareza, caminhos possíveis e próximos passos práticos para sua operação evoluir.'];const cards=Array.from(document.querySelectorAll<HTMLElement>('.service-card'));const originals=cards.map(card=>card.querySelector('p')?.textContent||'');const update=(event:Event)=>{const card=event.currentTarget as HTMLElement;const index=cards.indexOf(card);const p=card.querySelector('p');if(p)p.textContent=card.classList.contains('is-open')?`${originals[index]}\n\n${details[index]}`:originals[index];};cards.forEach(card=>card.addEventListener('click',update));return()=>cards.forEach(card=>card.removeEventListener('click',update));},[]);
 return <main>
  <nav><a className="brand" href="#inicio" aria-label="Salutar"><BrandMark className="brand-mark"/><span>SALUTAR<span className="dot">.</span></span></a><div className="nav-links"><a href="#servicos">Serviços</a><a href="/sobre">Sobre nós</a><a href="/contato">Contato</a></div><a className="nav-cta" href="https://wa.me/553192288682?text=Ol%C3%A1%20Salutar%2C%20quero%20iniciar%20um%20projeto." target="_blank" rel="noreferrer">Vamos conversar <ArrowUpRight size={16}/></a><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">{menu?<X/>:<Menu/>}</button></nav>
  {menu&&<div className="mobile-menu"><a onClick={()=>setMenu(false)} href="#servicos">Serviços</a><a onClick={()=>setMenu(false)} href="/sobre">Sobre nós</a><a onClick={()=>setMenu(false)} href="/contato">Contato</a></div>}
  <section className="hero" id="inicio"><div className="hero-copy"><motion.p initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="eyebrow"><Sparkles size={14}/> Marketing, criação & movimento</motion.p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.1}}>Marcas vivas<br/>movem <em>mundos.</em></motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}} className="hero-text">Estratégia, criatividade e performance para negócios que não nasceram para ficar parados.</motion.p><motion.a initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.35}} href="#contato" className="big-link">Começar um projeto <span><ArrowDownRight/></span></motion.a></div><div className="hero-art"><OrbitScene/><div className="orb-label label-one">ideias em órbita</div><div className="orb-label label-two">crescimento real</div><div className="scroll-note">role para descobrir <ArrowDownRight size={14}/></div></div></section>
  <section className="trust"><p>Uma agência para negócios que querem ir além do óbvio.</p><div className="trust-numbers"><span><b>360°</b> visão integrada</span><span><b>7</b> soluções criativas</span><span><b>100%</b> feita para crescer</span></div></section>
  <section className="services section" id="servicos"><div className="section-intro"><p className="eyebrow dark"><span>02</span> O que fazemos</p><h2>Uma ideia só ganha força<br/>quando encontra <em>direção.</em></h2></div><div className="service-grid">{services.map(([number,title,text,Icon,color],i)=><motion.article initial={{opacity:0,y:26}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} className={`service-card ${color}`} key={title}><div className="service-top"><span>{number}</span><Icon size={24}/></div><div><h3>{title}</h3><p>{text}</p></div><a href="#contato" aria-label={`Conhecer ${title}`}><ArrowUpRight size={20}/></a></motion.article>)}</div></section>
  <section className="marquee"><div ref={ticker}><span>ESTRATÉGIA <i>✦</i> CRIATIVIDADE <i>✦</i> PERFORMANCE <i>✦</i> CONEXÃO <i>✦</i> ESTRATÉGIA <i>✦</i> CRIATIVIDADE <i>✦</i> PERFORMANCE <i>✦</i> CONEXÃO <i>✦</i></span></div></section>
  <section className="about section" id="sobre"><div className="about-graphic"><div className="circle-word">SALUTAR · SALUTAR · SALUTAR · SALUTAR ·</div><BrandMark className="about-mark"/></div><div className="about-copy"><p className="eyebrow"><span>03</span> A Salutar</p><h2>Não fazemos barulho.<br/>Fazemos <em>presença.</em></h2><p>Somos uma agência que une análise, repertório e inquietação. Acreditamos que cada ponto de contato é uma oportunidade de fazer uma marca ser sentida — não apenas vista.</p><a href="#contato" className="big-link">Conheça nossa visão <span><ArrowDownRight/></span></a></div></section>
  <section className="contact" id="contato"><p className="eyebrow"><span>04</span> Seu próximo movimento</p><h2>Vamos fazer algo<br/><em>memorável?</em></h2><div className="contact-links"><a href="mailto:salutarwork@gmail.com" className="contact-email">salutarwork@gmail.com <Send size={26}/></a><a href="https://wa.me/553192288682" target="_blank" rel="noreferrer" className="contact-phone">+55 31 9228-8682 <ArrowUpRight size={20}/></a></div><div className="contact-footer"><span>© 2026 Salutar</span><span>Belo Horizonte · Brasil</span><div><a href="#inicio">Instagram</a><a href="mailto:salutarwork@gmail.com">E-mail</a></div></div></section>
 </main>;
}
